type Producto {
    _id: ID!,
    name: String,
    price: Int,
    image: String,
    category: String
}

type Query{
    obtenerProductos: [Producto],
    obtenerProductoPorId(id: String):Producto,

}



input UpdateProductPayload {
     id: String,
    name: String,
    price: Int,
    image: String,
    category: String
}

type Mutation {
    agregarProducto(name: String, price: Int, image: String, category: String): Producto
    updateProduct(producto: UpdateProductPayload): Producto
    deleteProduct(id: String): String
}